# This code works perfectly fine, but the image size is very large.
# We create a new Dockerfile inside the app folder.

# FROM nginx

# LABEL MAINTAINER=abhishek@sparta

#  COPY app /home/
#  COPY environment /home/

#  EXPOSE 80
#  EXPOSE 3000

#  RUN apt-get update
#  RUN apt-get install -y
#  RUN apt-get install software-properties-common -y
#  RUN apt-get install npm -y

#  CMD ["nginx", "-g", "daemon off;"]
  
#  WORKDIR /home/app
  
#  RUN npm install
#  CMD ["npm", "start"]
